package org.netlib;

import com.google.common.collect.Lists;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.stringtemplate.v4.ST;

import java.lang.reflect.Method;
import java.util.List;

@Mojo(
        name = "interface",
        defaultPhase = LifecyclePhase.GENERATE_SOURCES,
        requiresDependencyResolution = ResolutionScope.COMPILE
)
public class JavaInterfaceGenerator extends AbstractJavaGenerator {

    /**
     * The interface that we are implementing.
     */
    @Parameter(required = true)
    protected String fallback;

    @Override
    protected String generate(List<Method> methods) throws Exception {
        List<String> members = Lists.newArrayList();
        for (Method method : methods) {
            ST m = jTemplates.getInstanceOf("abstractMethod");
            m.add("return", method.getReturnType());
            m.add("method", method.getName());
            m.add("params", getNetlibJavaParameters(method));
            members.add(m.render());
        }

        ST t = jTemplates.getInstanceOf("abstractClass");
        t.add("package", getTargetPackage());
        t.add("name", getTargetClassName());
        t.add("members", members);
        t.add("docs", "Generated by " + getClass().getCanonicalName());
        t.add("fallback", fallback);

        return t.render();
    }
}
